name: Test
on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "run"
        run: |
          pwd 
          ls

      #    - name: clone KubeSphere repository
      #      uses: sudosubin/git-clone-action@v1
      #      with:
      #        repository: 'kubesphere/helm-charts'
      #        platform: 'github'

      - name: "run"
        run: |
          pwd 
          ls

      - name: copy helm chart
        run: |
          mkdir -p  chart/templates
          touch chart/deployment.yml chart/service.yml chart/ingress.yml 
          echo a > chart/deployment.yml
          echo b > chart/service.yml
          echo c > chart/ingress.yml 
          touch NOTES.txt 
          echo notes > NOTES.txt

      - name: "run"
        run: |
          pwd 
          ls
      
      

      - name: Create pull request
        uses: kethavathsivanaik/publish-chart-kubesphere@v1
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          chart_dir: chart
          user_email: sivanaikk0903@gmail.com
          user_name: Kethavath Siva Naik 
      

      - uses: mxschmitt/action-tmate@v3
      
#      - name: copy helm chart 
#        run: |
#          echo ${{ secrets.TOKEN }} | gh auth login --with-token
#          gh repo fork kubesphere/helm-charts --clone
#          cd helm-charts
#          git checkout -b meshery-helm-release
#          cp -r ./../hello  src/main/
          
 
#      - name: Create Pull Request
#        id: cpr
#        uses: peter-evans/create-pull-request@v3
#        with:
#          commit-message: "Created release note file ${{ steps.release_drafter.outputs.tag_name }}.md"
#          committer: l5io <ci@layer5.io>
#          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#          signoff: true
