name: Test
on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "meshery/meshery"

      - name: "run"
        run: |
          pwd 
          ls

      #    - name: clone KubeSphere repository
      #      uses: sudosubin/git-clone-action@v1
      #      with:
      #        repository: 'kubesphere/helm-charts'
      #        platform: 'github'

      - name: "run"
        run: |
          pwd 
          ls

      - name: copy helm chart
        run: |
          git clone https://www.github.com/kubesphere/helm-charts
          cd helm-charts
          git checkout -b meshery-helm-release
          cp -r ./../install/kubernetes/helm/meshery/  src/main/

      - name: "run"
        run: |
          pwd 
          ls

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Created release note file ${{ steps.release_drafter.outputs.tag_name }}.md"
          committer: l5io <ci@layer5.io>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true

      - uses: mxschmitt/action-tmate@v3
